# Generated by Django 5.0.1 on 2025-01-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tamabot", "0008_thread_last_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="therapist",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
