# Generated by Django 5.0.1 on 2024-12-03 15:06

import apps.common.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=apps.common.model_fields.AppPhoneNumberField(
                blank=True, default=None, max_length=128, null=True, region=None, unique=True
            ),
        ),
    ]
