version: "3"

services:
  postgres:
    image: ankane/pgvector:latest-pg17
    container_name: postgres-container
    env_file:
      - ../../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
